language: node_js
before_install:
  - sudo pip install -v Django==1.7
  - npm install -g grunt-cli
  - npm uninstall grunt # https://github.com/npm/npm/issues/3958
node_js: 
  - "0.12" 
  - "4.4" 
  - "5.x" 
python:
  - "2.7"
after_script:
  - npm install -g istanbul
  - npm run coveralls